回调函数惯例：
+ callback 的第一个参数是为了错误发生而保留的。一旦发生错误，callback(err) 就会被调用。（错误优先）
+ 第二个参数（如果有需要）用于成功的结果。此时 callback(null, result1, result2…) 将被调用。
因此单个 callback 函数可以同时具有报告错误以及传递返回结果的作用。

回调函数的问题
1. 回调错误难以处理 回调函数发生错误时，无法使用内置的构造函数来处理(即try-catch方式), 常出现错误丢失问题。为了解决这个问题，不同的库定义了各自的报错规约。如在Node中，回调函数一般具有两个参数: error和data。当有错误发生时，error将时非空值。
2. 多任务处理比较棘手 相互依赖需要顺序执行的任务,常常需要层层嵌套，导致代码复杂度变高，难以理解。对于无相互依赖,需要并行执行的任务,其错误处理和执行结果检查也比较麻烦。